/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { P2PListingWhereUniqueInput } from "./P2PListingWhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class DeleteP2PListingArgs {
  @ApiProperty({
    required: true,
    type: () => P2PListingWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => P2PListingWhereUniqueInput)
  @Field(() => P2PListingWhereUniqueInput, { nullable: false })
  where!: P2PListingWhereUniqueInput;
}

export { DeleteP2PListingArgs as DeleteP2PListingArgs };
