/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { P2PListingService } from "../p2PListing.service";
import { P2PListingCreateInput } from "./P2PListingCreateInput";
import { P2PListing } from "./P2PListing";
import { P2PListingFindManyArgs } from "./P2PListingFindManyArgs";
import { P2PListingWhereUniqueInput } from "./P2PListingWhereUniqueInput";
import { P2PListingUpdateInput } from "./P2PListingUpdateInput";

export class P2PListingControllerBase {
  constructor(protected readonly service: P2PListingService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: P2PListing })
  async createP2PListing(
    @common.Body() data: P2PListingCreateInput
  ): Promise<P2PListing> {
    return await this.service.createP2PListing({
      data: {
        ...data,

        wallet: data.wallet
          ? {
              connect: data.wallet,
            }
          : undefined,
      },
      select: {
        amount: true,
        createdAt: true,
        id: true,
        listingType: true,
        price: true,
        status: true,
        updatedAt: true,

        wallet: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [P2PListing] })
  @ApiNestedQuery(P2PListingFindManyArgs)
  async p2PListings(@common.Req() request: Request): Promise<P2PListing[]> {
    const args = plainToClass(P2PListingFindManyArgs, request.query);
    return this.service.p2PListings({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        id: true,
        listingType: true,
        price: true,
        status: true,
        updatedAt: true,

        wallet: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: P2PListing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async p2PListing(
    @common.Param() params: P2PListingWhereUniqueInput
  ): Promise<P2PListing | null> {
    const result = await this.service.p2PListing({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        id: true,
        listingType: true,
        price: true,
        status: true,
        updatedAt: true,

        wallet: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: P2PListing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateP2PListing(
    @common.Param() params: P2PListingWhereUniqueInput,
    @common.Body() data: P2PListingUpdateInput
  ): Promise<P2PListing | null> {
    try {
      return await this.service.updateP2PListing({
        where: params,
        data: {
          ...data,

          wallet: data.wallet
            ? {
                connect: data.wallet,
              }
            : undefined,
        },
        select: {
          amount: true,
          createdAt: true,
          id: true,
          listingType: true,
          price: true,
          status: true,
          updatedAt: true,

          wallet: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: P2PListing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteP2PListing(
    @common.Param() params: P2PListingWhereUniqueInput
  ): Promise<P2PListing | null> {
    try {
      return await this.service.deleteP2PListing({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          id: true,
          listingType: true,
          price: true,
          status: true,
          updatedAt: true,

          wallet: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
