/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsNumber,
  Min,
  Max,
  IsOptional,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { EnumP2PListingListingType } from "./EnumP2PListingListingType";
import { EnumP2PListingStatus } from "./EnumP2PListingStatus";
import { WalletWhereUniqueInput } from "../../wallet/base/WalletWhereUniqueInput";
import { Type } from "class-transformer";

@InputType()
class P2PListingCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  amount?: number | null;

  @ApiProperty({
    required: false,
    enum: EnumP2PListingListingType,
  })
  @IsEnum(EnumP2PListingListingType)
  @IsOptional()
  @Field(() => EnumP2PListingListingType, {
    nullable: true,
  })
  listingType?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    enum: EnumP2PListingStatus,
  })
  @IsEnum(EnumP2PListingStatus)
  @IsOptional()
  @Field(() => EnumP2PListingStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => WalletWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => WalletWhereUniqueInput)
  @IsOptional()
  @Field(() => WalletWhereUniqueInput, {
    nullable: true,
  })
  wallet?: WalletWhereUniqueInput | null;
}

export { P2PListingCreateInput as P2PListingCreateInput };
