/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { P2PListing } from "./P2PListing";
import { P2PListingCountArgs } from "./P2PListingCountArgs";
import { P2PListingFindManyArgs } from "./P2PListingFindManyArgs";
import { P2PListingFindUniqueArgs } from "./P2PListingFindUniqueArgs";
import { CreateP2PListingArgs } from "./CreateP2PListingArgs";
import { UpdateP2PListingArgs } from "./UpdateP2PListingArgs";
import { DeleteP2PListingArgs } from "./DeleteP2PListingArgs";
import { Wallet } from "../../wallet/base/Wallet";
import { P2PListingService } from "../p2PListing.service";
@graphql.Resolver(() => P2PListing)
export class P2PListingResolverBase {
  constructor(protected readonly service: P2PListingService) {}

  async _p2PListingsMeta(
    @graphql.Args() args: P2PListingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [P2PListing])
  async p2PListings(
    @graphql.Args() args: P2PListingFindManyArgs
  ): Promise<P2PListing[]> {
    return this.service.p2PListings(args);
  }

  @graphql.Query(() => P2PListing, { nullable: true })
  async p2PListing(
    @graphql.Args() args: P2PListingFindUniqueArgs
  ): Promise<P2PListing | null> {
    const result = await this.service.p2PListing(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => P2PListing)
  async createP2PListing(
    @graphql.Args() args: CreateP2PListingArgs
  ): Promise<P2PListing> {
    return await this.service.createP2PListing({
      ...args,
      data: {
        ...args.data,

        wallet: args.data.wallet
          ? {
              connect: args.data.wallet,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => P2PListing)
  async updateP2PListing(
    @graphql.Args() args: UpdateP2PListingArgs
  ): Promise<P2PListing | null> {
    try {
      return await this.service.updateP2PListing({
        ...args,
        data: {
          ...args.data,

          wallet: args.data.wallet
            ? {
                connect: args.data.wallet,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => P2PListing)
  async deleteP2PListing(
    @graphql.Args() args: DeleteP2PListingArgs
  ): Promise<P2PListing | null> {
    try {
      return await this.service.deleteP2PListing(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Wallet, {
    nullable: true,
    name: "wallet",
  })
  async getWallet(
    @graphql.Parent() parent: P2PListing
  ): Promise<Wallet | null> {
    const result = await this.service.getWallet(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
