/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  P2PListing as PrismaP2PListing,
  Wallet as PrismaWallet,
} from "@prisma/client";

export class P2PListingServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.P2PListingCountArgs, "select">
  ): Promise<number> {
    return this.prisma.p2PListing.count(args);
  }

  async p2PListings(
    args: Prisma.P2PListingFindManyArgs
  ): Promise<PrismaP2PListing[]> {
    return this.prisma.p2PListing.findMany(args);
  }
  async p2PListing(
    args: Prisma.P2PListingFindUniqueArgs
  ): Promise<PrismaP2PListing | null> {
    return this.prisma.p2PListing.findUnique(args);
  }
  async createP2PListing(
    args: Prisma.P2PListingCreateArgs
  ): Promise<PrismaP2PListing> {
    return this.prisma.p2PListing.create(args);
  }
  async updateP2PListing(
    args: Prisma.P2PListingUpdateArgs
  ): Promise<PrismaP2PListing> {
    return this.prisma.p2PListing.update(args);
  }
  async deleteP2PListing(
    args: Prisma.P2PListingDeleteArgs
  ): Promise<PrismaP2PListing> {
    return this.prisma.p2PListing.delete(args);
  }

  async getWallet(parentId: string): Promise<PrismaWallet | null> {
    return this.prisma.p2PListing
      .findUnique({
        where: { id: parentId },
      })
      .wallet();
  }
}
