/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { P2PListingWhereInput } from "./P2PListingWhereInput";
import { Type } from "class-transformer";

@ArgsType()
class P2PListingCountArgs {
  @ApiProperty({
    required: false,
    type: () => P2PListingWhereInput,
  })
  @Field(() => P2PListingWhereInput, { nullable: true })
  @Type(() => P2PListingWhereInput)
  where?: P2PListingWhereInput;
}

export { P2PListingCountArgs as P2PListingCountArgs };
