/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { P2PListingWhereInput } from "./P2PListingWhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { P2PListingOrderByInput } from "./P2PListingOrderByInput";

@ArgsType()
class P2PListingFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => P2PListingWhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => P2PListingWhereInput, { nullable: true })
  @Type(() => P2PListingWhereInput)
  where?: P2PListingWhereInput;

  @ApiProperty({
    required: false,
    type: [P2PListingOrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [P2PListingOrderByInput], { nullable: true })
  @Type(() => P2PListingOrderByInput)
  orderBy?: Array<P2PListingOrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { P2PListingFindManyArgs as P2PListingFindManyArgs };
