/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { P2PListingWhereInput } from "./P2PListingWhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class P2PListingListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => P2PListingWhereInput,
  })
  @ValidateNested()
  @Type(() => P2PListingWhereInput)
  @IsOptional()
  @Field(() => P2PListingWhereInput, {
    nullable: true,
  })
  every?: P2PListingWhereInput;

  @ApiProperty({
    required: false,
    type: () => P2PListingWhereInput,
  })
  @ValidateNested()
  @Type(() => P2PListingWhereInput)
  @IsOptional()
  @Field(() => P2PListingWhereInput, {
    nullable: true,
  })
  some?: P2PListingWhereInput;

  @ApiProperty({
    required: false,
    type: () => P2PListingWhereInput,
  })
  @ValidateNested()
  @Type(() => P2PListingWhereInput)
  @IsOptional()
  @Field(() => P2PListingWhereInput, {
    nullable: true,
  })
  none?: P2PListingWhereInput;
}
export { P2PListingListRelationFilter as P2PListingListRelationFilter };
