/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { P2PListingWhereUniqueInput } from "../../p2PListing/base/P2PListingWhereUniqueInput";
import { ApiProperty } from "@nestjs/swagger";

@InputType()
class P2PListingUpdateManyWithoutWalletsInput {
  @Field(() => [P2PListingWhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [P2PListingWhereUniqueInput],
  })
  connect?: Array<P2PListingWhereUniqueInput>;

  @Field(() => [P2PListingWhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [P2PListingWhereUniqueInput],
  })
  disconnect?: Array<P2PListingWhereUniqueInput>;

  @Field(() => [P2PListingWhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [P2PListingWhereUniqueInput],
  })
  set?: Array<P2PListingWhereUniqueInput>;
}

export { P2PListingUpdateManyWithoutWalletsInput as P2PListingUpdateManyWithoutWalletsInput };
