/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsNumber,
  Min,
  Max,
  IsOptional,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { EnumWalletCurrency } from "./EnumWalletCurrency";
import { P2PListingCreateNestedManyWithoutWalletsInput } from "./P2PListingCreateNestedManyWithoutWalletsInput";
import { Type } from "class-transformer";
import { TransactionCreateNestedManyWithoutWalletsInput } from "./TransactionCreateNestedManyWithoutWalletsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class WalletCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  balance?: number | null;

  @ApiProperty({
    required: false,
    enum: EnumWalletCurrency,
  })
  @IsEnum(EnumWalletCurrency)
  @IsOptional()
  @Field(() => EnumWalletCurrency, {
    nullable: true,
  })
  currency?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => P2PListingCreateNestedManyWithoutWalletsInput,
  })
  @ValidateNested()
  @Type(() => P2PListingCreateNestedManyWithoutWalletsInput)
  @IsOptional()
  @Field(() => P2PListingCreateNestedManyWithoutWalletsInput, {
    nullable: true,
  })
  p2PListings?: P2PListingCreateNestedManyWithoutWalletsInput;

  @ApiProperty({
    required: false,
    type: () => TransactionCreateNestedManyWithoutWalletsInput,
  })
  @ValidateNested()
  @Type(() => TransactionCreateNestedManyWithoutWalletsInput)
  @IsOptional()
  @Field(() => TransactionCreateNestedManyWithoutWalletsInput, {
    nullable: true,
  })
  transactions?: TransactionCreateNestedManyWithoutWalletsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { WalletCreateInput as WalletCreateInput };
